spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flight_advisor
    username: ${DB_USERNAME:ivanm}
    password: ${DB_PASSWORD:rand0mpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 50
    hibernate:
      ddl-auto: create
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT:flight-advisor-app}
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URI:http://localhost:9000/realms/flight-advisor-realm}
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URI:http://localhost:9000/realms/flight-advisor-realm}

server:
  search:
    depth: ${ROUTE_SEARCH_DEPTH:2} #do not set value above 3, it will slow searching of routes
    type: ${ROUTE_SEARCH_TYPE:STANDARD}

logging:
  level:
    root: WARN