spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flight_advisor
    username: ivanm
    password: rand0mpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 50
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  search:
    depth: 2 #do not set value above 3, it will slow searching of routes
logging:
  level:
    root: WARN