spring:
  datasource:
    url: jdbc:h2:mem:flight_advisor;IGNORECASE=TRUE
    username: ivanm
    password: "Rand0mP4$$word"
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-ui